/**
 * legalpass-tool - MCP exposure for LegalPass.
 *
 * LegalPass is an issue-spotter only. These handlers expose the existing
 * LegalPass guardrails to MCP callers without pretending a full legal review
 * engine exists yet.
 */

import { createHash } from "node:crypto";
import yaml from "js-yaml";

type DisclaimerLength = "chat" | "results" | "tos";
type LegalPassMcpVerdict = "check" | "fail" | "na" | "other" | "pending";
type LegalPassMcpTargetKind = "url" | "contract_upload" | "repo";
type LegalPassMcpProfile = "smoke" | "standard" | "deep";
type LegalPassMcpJurisdiction = "AU" | "EU" | "US-CA" | "US-NY" | "UK" | "CA" | "NZ" | "SG";
type LegalPassMcpHatId =
  | "privacy"
  | "consumer_tos"
  | "contracts"
  | "oss_licence"
  | "ai_ethics"
  | "ip"
  | "marketing_claims"
  | "litigator"
  | "plain_english"
  | "compliance"
  | "jurisdiction_router"
  | "citation_verifier";

interface LegalPassMcpTarget {
  kind: LegalPassMcpTargetKind;
  url?: string;
  upload_ref?: string;
  repo?: string;
  branch?: string;
  commit?: string;
}

interface LegalPassMcpItem {
  item_id: string;
  title: string;
  severity: "high" | "medium" | "low";
  verdict: LegalPassMcpVerdict;
  finding: string;
  evidence: Array<{ source: string; excerpt: string; url?: string }>;
  on_fail_comment?: string;
}

interface LegalPassMcpSummary {
  total: number;
  check: number;
  fail: number;
  na: number;
  other: number;
  pending: number;
  pass_rate: number;
}

interface LegalPassMcpRunRecord {
  status: "complete" | "planned";
  pass: "legalpass";
  run_id: string;
  pack_id: string;
  target: LegalPassMcpTarget;
  profile: LegalPassMcpProfile;
  jurisdictions: LegalPassMcpJurisdiction[];
  summary: LegalPassMcpSummary;
  items: LegalPassMcpItem[];
  disclaimer: string;
  note: string;
  safety: {
    issue_spotter_only: true;
    no_legal_advice: true;
    no_transactional_instrument: true;
  };
  audit_log: Array<Record<string, unknown>>;
}

interface LegalPassMcpPack {
  id: string;
  targets: LegalPassMcpTargetKind[];
  jurisdictions?: LegalPassMcpJurisdiction[];
  profile?: LegalPassMcpProfile;
  hats: Array<{ hat_id?: LegalPassMcpHatId; enabled?: boolean }>;
  items?: unknown[];
  [key: string]: unknown;
}

const SUPPORTED_TARGET_KINDS = new Set<LegalPassMcpTargetKind>([
  "url",
  "contract_upload",
  "repo",
]);

const SUPPORTED_HAT_IDS = new Set<LegalPassMcpHatId>([
  "privacy",
  "consumer_tos",
  "contracts",
  "oss_licence",
  "ai_ethics",
  "ip",
  "marketing_claims",
  "litigator",
  "plain_english",
  "compliance",
  "jurisdiction_router",
  "citation_verifier",
]);

const SUPPORTED_PROFILES = new Set<LegalPassMcpProfile>(["smoke", "standard", "deep"]);
const SUPPORTED_JURISDICTIONS = new Set<LegalPassMcpJurisdiction>([
  "AU",
  "EU",
  "US-CA",
  "US-NY",
  "UK",
  "CA",
  "NZ",
  "SG",
]);
const DEFAULT_PROFILE: LegalPassMcpProfile = "standard";
const DEFAULT_JURISDICTIONS: LegalPassMcpJurisdiction[] = ["AU", "EU", "US-CA"];

const DISCLAIMERS: Record<DisclaimerLength, string> = {
  chat:
    "LegalPass gives general legal information about contracts, not legal advice. " +
    "We are not a law firm. Using LegalPass does not create a lawyer-client " +
    "relationship. Laws change and vary by location. For decisions that " +
    "matter, talk to a qualified lawyer in your jurisdiction.",
  results:
    "Heads up: LegalPass is an information tool, not a law firm. The verdict " +
    "you are reading is generated by AI from patterns in similar documents. " +
    "It is not legal advice, not an opinion on your rights, and not a " +
    "substitute for review by a qualified lawyer. Your use of LegalPass does " +
    "not create a lawyer-client, solicitor-client or attorney-client " +
    "relationship, and what you tell us is not protected by legal " +
    "professional privilege. Laws change. They differ between countries, " +
    "states, and territories. For anything important, especially anything " +
    "you plan to sign, send, or rely on, please get advice from a lawyer " +
    "qualified in your jurisdiction before acting on that information.",
  tos:
    "LegalPass is a software tool operated by UnClick Operations Pty Ltd. It " +
    "scans contracts, terms of service, privacy policies, end-user licence " +
    "agreements, intellectual property agreements, and similar documents, " +
    "and produces a plain-English summary, called a verdict, that compares " +
    "clauses in your document with patterns observed in similar documents. " +
    "UnClick Operations Pty Ltd is not a law firm. It is not a regulated " +
    "legal practice in Australia, the United States, the United Kingdom, or " +
    "any other jurisdiction. Its directors and employees are not acting as " +
    "your lawyer, solicitor, or attorney. LegalPass cannot and does not give " +
    "legal advice, opinions, or recommendations about your legal rights, " +
    "remedies, defences, options, or strategies. LegalPass does not apply " +
    "law to the facts of your situation. Your use of LegalPass does not " +
    "create a lawyer-client, solicitor-client, or attorney-client relationship " +
    "between you and UnClick Operations Pty Ltd or anyone working for UnClick " +
    "Operations Pty Ltd. Information you upload or type into LegalPass is not " +
    "protected by legal professional privilege, attorney-client privilege, or " +
    "any equivalent doctrine. The verdict is informational only. It is " +
    "generated by artificial intelligence and may contain errors, omissions, " +
    "or out-of-date material. Laws change frequently. They vary between " +
    "countries, states, territories, and even between municipalities. A clause " +
    "that is common in one jurisdiction may be unusual or unenforceable in " +
    "another. You are responsible for confirming whether information in a " +
    "verdict is current and applies to your situation. Before you sign, send, " +
    "or rely on any document, get advice from a lawyer qualified in the " +
    "jurisdiction whose laws apply. LegalPass offers a Talk to a Lawyer " +
    "feature that introduces you to independent lawyers. Those lawyers are " +
    "not employees or agents of UnClick Operations Pty Ltd. Any engagement you " +
    "enter is between you and that lawyer. By using LegalPass you acknowledge " +
    "and accept these limits. To the maximum extent permitted by law, you use " +
    "LegalPass at your own risk.",
};

const FORBIDDEN_PHRASES: ReadonlyArray<{ phrase: string; reason: string }> = [
  { phrase: "should", reason: "directive verb - implies a recommendation" },
  { phrase: "must", reason: "directive verb - implies an obligation" },
  { phrase: "you need to", reason: "directive phrasing - implies an instruction" },
  { phrase: "you have to", reason: "directive phrasing - implies an instruction" },
  { phrase: "you are obligated", reason: "directive phrasing - implies a legal obligation" },
  { phrase: "do this", reason: "directive phrasing - implies an instruction" },
  { phrase: "ask a qualified lawyer", reason: "directive legal referral phrasing - prohibited in verdict text" },
  { phrase: "ask a qualified practitioner", reason: "directive legal referral phrasing - prohibited in verdict text" },
  { phrase: "talk to a qualified lawyer", reason: "directive legal referral phrasing - prohibited in verdict text" },
  { phrase: "get advice from a lawyer", reason: "directive legal referral phrasing - prohibited in verdict text" },
  { phrase: "you may want to review with a lawyer", reason: "user-directed legal referral phrasing - prohibited in verdict text" },
  { phrase: "we recommend", reason: "first-person recommendation - prohibited" },
  { phrase: "the right thing to do is", reason: "normative recommendation - prohibited" },
  { phrase: "this is illegal", reason: "definitive legal conclusion - prohibited" },
  { phrase: "this is enforceable", reason: "definitive legal conclusion - prohibited" },
  { phrase: "this is unenforceable", reason: "definitive legal conclusion - prohibited" },
  { phrase: "this is lawful", reason: "definitive legal conclusion - prohibited" },
  { phrase: "this is compliant", reason: "unsupported compliance conclusion - prohibited" },
  { phrase: "safe to sign", reason: "transactional safety conclusion - prohibited" },
  { phrase: "safe to publish", reason: "publication safety conclusion - prohibited" },
  { phrase: "safe to rely on", reason: "reliance safety conclusion - prohibited" },
  { phrase: "legally safe", reason: "unsupported legal safety claim - prohibited" },
  { phrase: "no legal risk", reason: "unsupported risk-clearance claim - prohibited" },
  { phrase: "no legal issues", reason: "unsupported risk-clearance claim - prohibited" },
  { phrase: "you will win", reason: "outcome prediction - prohibited" },
  { phrase: "you will lose", reason: "outcome prediction - prohibited" },
  { phrase: "robot lawyer", reason: "substitute-for-lawyer claim - prohibited" },
  { phrase: "ai lawyer", reason: "substitute-for-lawyer claim - prohibited" },
  { phrase: "replace your lawyer", reason: "substitute-for-lawyer claim - prohibited" },
  { phrase: "automatic compliance", reason: "unsupported compliance claim - prohibited" },
  { phrase: "guaranteed compliant", reason: "unsupported compliance claim - prohibited" },
  { phrase: "fully compliant", reason: "unsupported compliance claim - prohibited" },
  { phrase: "we represent you", reason: "legal representation claim - prohibited" },
  { phrase: "100% compliant", reason: "unsupported compliance claim - prohibited" },
];

const ALLOWED_PHRASES = [
  "appears",
  "seems",
  "may",
  "might",
  "could",
  "consider",
  "in similar contracts",
  "in comparable agreements",
  "is unusual",
  "is common",
  "is typical",
  "is standard",
  "merits attention",
  "warrants review",
  "qualified practitioner review may be warranted",
  "the regulatory landscape",
];

const FIXTURE_CHECKS: ReadonlyArray<{
  id: string;
  title: string;
  severity: "high" | "medium" | "low";
  terms: string[];
  finding: string;
}> = [
  {
    id: "privacy-controller-contact",
    title: "Controller or operator contact path",
    severity: "high",
    terms: ["contact", "privacy"],
    finding: "The public fixture text did not include the configured privacy contact signal.",
  },
  {
    id: "privacy-data-use",
    title: "Data collection and use disclosure",
    severity: "high",
    terms: ["collect", "use"],
    finding: "The public fixture text did not include the configured data collection and use signal.",
  },
  {
    id: "privacy-retention-transfer",
    title: "Retention or transfer disclosure",
    severity: "medium",
    terms: ["retain", "third party"],
    finding: "The public fixture text did not include the configured retention or transfer signal.",
  },
  {
    id: "tos-liability-indemnity",
    title: "Liability and indemnity visibility",
    severity: "high",
    terms: ["liability", "indemnity"],
    finding: "The public fixture text did not include the configured liability and indemnity signal.",
  },
  {
    id: "tos-variation-termination",
    title: "Variation or termination signal",
    severity: "medium",
    terms: ["terminate", "change"],
    finding: "The public fixture text did not include the configured variation or termination signal.",
  },
  {
    id: "tos-dispute-contact",
    title: "Dispute or support contact path",
    severity: "medium",
    terms: ["dispute", "support"],
    finding: "The public fixture text did not include the configured dispute or support signal.",
  },
  {
    id: "oss-manifest-licence",
    title: "Dependency licence manifest",
    severity: "high",
    terms: ["license", "dependency"],
    finding: "The public fixture text did not include the configured dependency licence signal.",
  },
  {
    id: "oss-attribution-copyleft",
    title: "Attribution or copyleft marker",
    severity: "medium",
    terms: ["attribution", "copyleft"],
    finding: "The public fixture text did not include the configured attribution or copyleft signal.",
  },
  {
    id: "oss-patent-notice",
    title: "Patent or notice signal",
    severity: "low",
    terms: ["patent", "notice"],
    finding: "The public fixture text did not include the configured patent or notice signal.",
  },
];

const DEFAULT_PACK: LegalPassMcpPack = {
  id: "legalpass-mvp-v0",
  targets: ["url", "contract_upload", "repo"],
  jurisdictions: DEFAULT_JURISDICTIONS,
  profile: DEFAULT_PROFILE,
  hats: [
    { hat_id: "privacy", enabled: true },
    { hat_id: "consumer_tos", enabled: true },
    { hat_id: "contracts", enabled: true },
    { hat_id: "oss_licence", enabled: true },
    { hat_id: "citation_verifier", enabled: true },
  ],
  items: [],
};

const packStore = new Map<string, LegalPassMcpPack>([[DEFAULT_PACK.id, DEFAULT_PACK]]);
const runStore = new Map<string, LegalPassMcpRunRecord>();

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function phrasePattern(phrase: string): RegExp {
  const escaped = phrase.trim().split(/\s+/).map(escapeRegex).join("\\s+");
  return new RegExp(`\\b${escaped}\\b`, "gi");
}

function disclaimerLength(value: unknown): DisclaimerLength {
  return value === "chat" || value === "tos" ? value : "results";
}

function normalizeText(value: string): string {
  return value.toLocaleLowerCase("en-US").replace(/\s+/g, " ").trim();
}

function buildRunId(input: unknown): string {
  return `legalpass_${createHash("sha256")
    .update(JSON.stringify(input))
    .digest("hex")
    .slice(0, 12)}`;
}

function packRunSignature(pack: LegalPassMcpPack): Record<string, unknown> {
  return {
    id: pack.id,
    targets: [...pack.targets].sort(),
    profile: pack.profile ?? DEFAULT_PROFILE,
    jurisdictions: [...(pack.jurisdictions ?? DEFAULT_JURISDICTIONS)].sort(),
    enabled_hats: pack.hats
      .filter((hat) => hat.enabled !== false)
      .map((hat) => hat.hat_id)
      .filter(Boolean)
      .sort(),
  };
}

function isSupportedTargetKind(value: string): value is LegalPassMcpTargetKind {
  return SUPPORTED_TARGET_KINDS.has(value as LegalPassMcpTargetKind);
}

function isSupportedHatId(value: string): value is LegalPassMcpHatId {
  return SUPPORTED_HAT_IDS.has(value as LegalPassMcpHatId);
}

function isSupportedProfile(value: string): value is LegalPassMcpProfile {
  return SUPPORTED_PROFILES.has(value as LegalPassMcpProfile);
}

function isSupportedJurisdiction(value: string): value is LegalPassMcpJurisdiction {
  return SUPPORTED_JURISDICTIONS.has(value as LegalPassMcpJurisdiction);
}

function firstDuplicate(values: string[]): string | null {
  const seen = new Set<string>();
  for (const value of values) {
    if (seen.has(value)) return value;
    seen.add(value);
  }
  return null;
}

function isValidUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

function summaryFromItems(items: LegalPassMcpItem[]): LegalPassMcpSummary {
  const summary: LegalPassMcpSummary = {
    total: items.length,
    check: 0,
    fail: 0,
    na: 0,
    other: 0,
    pending: 0,
    pass_rate: 0,
  };
  for (const item of items) {
    summary[item.verdict] += 1;
  }
  summary.pass_rate = summary.total === 0
    ? 0
    : Math.round((summary.check / summary.total) * 100);
  return summary;
}

function cloneRun(record: LegalPassMcpRunRecord): LegalPassMcpRunRecord {
  return structuredClone(record);
}

function saveRun(record: LegalPassMcpRunRecord): LegalPassMcpRunRecord {
  const existing = runStore.get(record.run_id);
  if (existing) {
    return cloneRun(existing);
  }

  runStore.set(record.run_id, cloneRun(record));
  return cloneRun(record);
}

function fixtureChecksForPack(pack: LegalPassMcpPack): typeof FIXTURE_CHECKS {
  const enabledHatIds = new Set(
    pack.hats
      .filter((hat) => hat.enabled !== false)
      .map((hat) => hat.hat_id),
  );
  return FIXTURE_CHECKS.filter((check) => {
    if (check.id.startsWith("privacy-")) return enabledHatIds.has("privacy");
    if (check.id.startsWith("tos-")) {
      return enabledHatIds.has("consumer_tos") || enabledHatIds.has("contracts");
    }
    if (check.id.startsWith("oss-")) return enabledHatIds.has("oss_licence");
    return false;
  });
}

function fixtureSummary(text: string, pack: LegalPassMcpPack) {
  const normalized = normalizeText(text);
  const checks = fixtureChecksForPack(pack);
  const items: LegalPassMcpItem[] = checks.map((check) => {
    const passed = check.terms.every((term) => normalized.includes(normalizeText(term)));
    return {
      item_id: check.id,
      title: check.title,
      severity: check.severity,
      verdict: passed ? "check" as const : "fail" as const,
      finding: passed
        ? `${check.title} appears in the public fixture text.`
        : `${check.finding} This is an issue-spotting flag only.`,
      evidence: [
        {
          source: "fixture_text",
          excerpt: `Checked public fixture text for ${check.terms.join(" + ")}.`,
        },
      ],
      on_fail_comment: passed
        ? undefined
        : "Issue-spotter flag only. Qualified practitioner review may be warranted before any action is taken.",
    };
  });
  return {
    summary: summaryFromItems(items),
    items,
  };
}

export function lintLegalPassVerdict(text: string): Array<{ phrase: string; index: number; reason: string }> {
  const issues: Array<{ phrase: string; index: number; reason: string }> = [];
  for (const { phrase, reason } of FORBIDDEN_PHRASES) {
    const pattern = phrasePattern(phrase);
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(text)) !== null) {
      issues.push({ phrase, index: match.index, reason });
    }
  }
  return issues.sort((a, b) => a.index - b.index);
}

export async function legalpassRun(args: Record<string, unknown>): Promise<unknown> {
  const packId = typeof args.pack_id === "string" && args.pack_id ? args.pack_id : "legalpass-mvp-v0";
  const pack = packStore.get(packId);
  if (!pack) {
    return { error: `pack '${packId}' was not found` };
  }
  const parsedTarget = parseTarget(args);
  if ("error" in parsedTarget) {
    return parsedTarget;
  }
  const target = parsedTarget.target;
  const parsedProfile = parseProfile(args.profile ?? pack.profile ?? DEFAULT_PROFILE, "profile");
  if ("error" in parsedProfile) return parsedProfile;
  const profile = parsedProfile.profile;
  const parsedJurisdictions = parseJurisdictions(
    args.jurisdictions ?? pack.jurisdictions ?? DEFAULT_JURISDICTIONS,
    "jurisdictions",
  );
  if ("error" in parsedJurisdictions) return parsedJurisdictions;
  const jurisdictions = parsedJurisdictions.jurisdictions;

  if (!pack.targets.includes(target.kind)) {
    return { error: `pack '${packId}' does not support target kind '${target.kind}'` };
  }
  const pack_signature = packRunSignature(pack);

  const fixtureText = typeof args.fixture_text === "string" ? args.fixture_text.trim() : "";
  if (fixtureText) {
    const fixture = fixtureSummary(fixtureText, pack);
    const record: LegalPassMcpRunRecord = {
      status: "complete",
      pass: "legalpass",
      run_id: buildRunId({ packId, pack_signature, target, profile, jurisdictions, fixtureText }),
      pack_id: packId,
      target,
      profile,
      jurisdictions,
      summary: fixture.summary,
      items: fixture.items,
      disclaimer: DISCLAIMERS.results,
      note:
        "LegalPass ran a deterministic public fixture issue-spotter pass. It did not fetch private data, draft legal text, or give legal advice.",
      safety: {
        issue_spotter_only: true,
        no_legal_advice: true,
        no_transactional_instrument: true,
      },
      audit_log: [],
    };
    return saveRun(record);
  }

  const runId = buildRunId({ packId, pack_signature, target, profile, jurisdictions, mode: "planned" });
  return saveRun({
    status: "planned",
    pass: "legalpass",
    run_id: runId,
    pack_id: packId,
    target,
    profile,
    jurisdictions,
    summary: summaryFromItems([]),
    items: [],
    disclaimer: DISCLAIMERS.chat,
    note:
      "LegalPass returned a guarded run plan because no public fixture text was provided. No private data was fetched and no legal advice was generated.",
    safety: {
      issue_spotter_only: true,
      no_legal_advice: true,
      no_transactional_instrument: true,
    },
    audit_log: [],
  });
}

function parseTarget(args: Record<string, unknown>):
  | { target: LegalPassMcpTarget }
  | { error: string } {
  if (args.target && typeof args.target === "object" && !Array.isArray(args.target)) {
    const raw = args.target as Record<string, unknown>;
    if (typeof raw.kind !== "string") {
      return { error: "target.kind or target_url is required" };
    }
    if (!isSupportedTargetKind(raw.kind)) {
      return { error: "target.kind must be url|contract_upload|repo" };
    }

    if (raw.kind === "url") {
      const url = typeof raw.url === "string" ? raw.url.trim() : "";
      if (!url || !isValidUrl(url)) {
        return { error: "target.url must be a valid http(s) URL" };
      }
      return { target: { kind: "url", url } };
    }

    if (raw.kind === "contract_upload") {
      const uploadRef = typeof raw.upload_ref === "string" ? raw.upload_ref.trim() : "";
      if (!uploadRef) {
        return { error: "target.upload_ref is required for contract_upload runs" };
      }
      return { target: { kind: "contract_upload", upload_ref: uploadRef } };
    }

    const repo = typeof raw.repo === "string" ? raw.repo.trim() : "";
    if (!repo) {
      return { error: "target.repo is required for repo runs" };
    }
    return {
      target: {
        kind: "repo",
        repo,
        ...(typeof raw.branch === "string" && raw.branch.trim() ? { branch: raw.branch.trim() } : {}),
        ...(typeof raw.commit === "string" && raw.commit.trim() ? { commit: raw.commit.trim() } : {}),
      },
    };
  }

  if (typeof args.target_url === "string" && args.target_url.trim()) {
    const url = args.target_url.trim();
    if (!isValidUrl(url)) {
      return { error: "target_url must be a valid http(s) URL" };
    }
    return { target: { kind: "url", url } };
  }

  return { error: "target.kind or target_url is required" };
}

function parseProfile(value: unknown, fieldName: string):
  | { profile: LegalPassMcpProfile }
  | { error: string } {
  if (typeof value !== "string" || !isSupportedProfile(value)) {
    return { error: `${fieldName} must be smoke|standard|deep` };
  }
  return { profile: value };
}

function parseJurisdictions(value: unknown, fieldName: string):
  | { jurisdictions: LegalPassMcpJurisdiction[] }
  | { error: string } {
  if (!Array.isArray(value) || value.length === 0) {
    return { error: `${fieldName} must be a non-empty array` };
  }
  const invalid = value.find((item) => typeof item !== "string" || !isSupportedJurisdiction(item));
  if (invalid !== undefined) {
    return { error: `${fieldName} may only include AU, EU, US-CA, US-NY, UK, CA, NZ, or SG` };
  }
  if (firstDuplicate(value as string[])) {
    return { error: `${fieldName} entries must be unique` };
  }
  return { jurisdictions: value as LegalPassMcpJurisdiction[] };
}

function parseOptionalText(value: unknown, fieldName: string):
  | { value?: string }
  | { error: string } {
  if (value === undefined || value === null) {
    return {};
  }
  if (typeof value !== "string") {
    return { error: `${fieldName} must be a string` };
  }
  const trimmed = value.trim();
  if (!trimmed) {
    return { error: `${fieldName} must not be blank` };
  }
  return { value: trimmed };
}

export async function legalpassVerdict(args: Record<string, unknown>): Promise<unknown> {
  const verdictText = typeof args.verdict_text === "string" ? args.verdict_text : "";
  const length = disclaimerLength(args.disclaimer_length);
  const issues = verdictText ? lintLegalPassVerdict(verdictText) : [];
  return {
    ok: issues.length === 0,
    safe_to_emit: issues.length === 0,
    issues,
    allowed_framing: ALLOWED_PHRASES,
    disclaimer_length: length,
    disclaimer: DISCLAIMERS[length],
  };
}

export async function legalpassStatus(args: Record<string, unknown>): Promise<unknown> {
  const runId = typeof args.run_id === "string" ? args.run_id.trim() : "";
  if (!runId) return { error: "run_id is required" };

  const record = runStore.get(runId);
  if (!record) return { error: `run '${runId}' was not found` };
  return cloneRun(record);
}

export async function legalpassSavePack(args: Record<string, unknown>): Promise<unknown> {
  const overwrite = args.overwrite === true;
  const parsedPack = parsePackInput(args);
  if ("error" in parsedPack) return parsedPack;

  const pack = parsedPack.pack;
  if (!overwrite && packStore.has(pack.id)) {
    return { error: `pack '${pack.id}' already exists; pass overwrite=true to update it` };
  }

  packStore.set(pack.id, structuredClone(pack));
  return {
    pack_id: pack.id,
    saved: true,
    item_count: Array.isArray(pack.items) ? pack.items.length : 0,
    hat_count: pack.hats.length,
  };
}

export async function legalpassEditItem(args: Record<string, unknown>): Promise<unknown> {
  const runId = typeof args.run_id === "string" ? args.run_id.trim() : "";
  const itemId = typeof args.item_id === "string" ? args.item_id.trim() : "";
  if (!runId) return { error: "run_id is required" };
  if (!itemId) return { error: "item_id is required" };

  const record = runStore.get(runId);
  if (!record) return { error: `run '${runId}' was not found` };
  const item = record.items.find((candidate) => candidate.item_id === itemId);
  if (!item) return { error: `item '${itemId}' was not found on run '${runId}'` };

  if (args.verdict !== undefined && typeof args.verdict !== "string") {
    return { error: "verdict must be check|fail|na|other|pending" };
  }
  const verdict = typeof args.verdict === "string" ? args.verdict.trim() : "";
  if (verdict && !["check", "fail", "na", "other", "pending"].includes(verdict)) {
    return { error: "verdict must be check|fail|na|other|pending" };
  }

  const parsedFinding = parseOptionalText(args.finding, "finding");
  if ("error" in parsedFinding) return parsedFinding;
  const finding = parsedFinding.value ?? "";
  const parsedOnFailComment = parseOptionalText(args.on_fail_comment, "on_fail_comment");
  if ("error" in parsedOnFailComment) return parsedOnFailComment;
  const onFailComment = parsedOnFailComment.value ?? "";
  const reviewerNoteSource = args.reviewer_note !== undefined ? args.reviewer_note : args.notes;
  const parsedReviewerNote = parseOptionalText(reviewerNoteSource, "reviewer_note");
  if ("error" in parsedReviewerNote) return parsedReviewerNote;
  const reviewerNote = parsedReviewerNote.value ?? "";
  if (!verdict && !finding && !onFailComment && !reviewerNote) {
    return { error: "provide verdict, finding, on_fail_comment, reviewer_note, or notes" };
  }

  const lintText = [finding, onFailComment, reviewerNote].filter(Boolean).join("\n");
  const issues = lintText ? lintLegalPassVerdict(lintText) : [];
  if (issues.length > 0) {
    return { error: "forbidden phrasing", issues };
  }

  const before = {
    verdict: item.verdict,
    finding: item.finding,
    on_fail_comment: item.on_fail_comment,
  };
  if (verdict) item.verdict = verdict as LegalPassMcpVerdict;
  if (finding) item.finding = finding;
  if (onFailComment) item.on_fail_comment = onFailComment;
  record.summary = summaryFromItems(record.items);
  const audit_entry = {
    event: "legalpass_item_edit",
    run_id: runId,
    item_id: itemId,
    actor_user_id: typeof args.actor_user_id === "string" && args.actor_user_id.trim()
      ? args.actor_user_id.trim()
      : "unknown",
    edited_at: new Date().toISOString(),
    before,
    after: {
      verdict: item.verdict,
      finding: item.finding,
      on_fail_comment: item.on_fail_comment,
    },
    ...(reviewerNote ? { reviewer_note: reviewerNote } : {}),
  };
  record.audit_log.push(audit_entry);
  runStore.set(runId, cloneRun(record));

  return {
    run_id: runId,
    item_id: itemId,
    updated: true,
    summary: record.summary,
    audit_entry,
  };
}

function parsePackInput(args: Record<string, unknown>):
  | { pack: LegalPassMcpPack }
  | { error: string } {
  let rawPack = args.pack;
  if (!rawPack && typeof args.yaml === "string") {
    try {
      rawPack = yaml.load(args.yaml);
    } catch (err) {
      return { error: `yaml parse failed: ${err instanceof Error ? err.message : String(err)}` };
    }
  }

  if (!rawPack || typeof rawPack !== "object" || Array.isArray(rawPack)) {
    return { error: "pack object or yaml is required" };
  }

  const pack = structuredClone(rawPack) as LegalPassMcpPack;
  if (typeof args.pack_id === "string" && args.pack_id.trim()) {
    pack.id = args.pack_id.trim();
  }
  if (typeof pack.id !== "string" || !pack.id.trim()) {
    return { error: "pack.id or pack_id is required" };
  }
  pack.id = pack.id.trim();

  if (!Array.isArray(pack.targets) || pack.targets.length === 0) {
    return { error: "pack.targets must include at least one target kind" };
  }
  const invalidTarget = pack.targets.find(
    (target) => typeof target !== "string" || !isSupportedTargetKind(target),
  );
  if (invalidTarget !== undefined) {
    return { error: "pack.targets may only include url, contract_upload, or repo" };
  }
  if (firstDuplicate(pack.targets)) {
    return { error: "pack.targets entries must be unique" };
  }
  const parsedPackProfile = parseProfile(pack.profile ?? DEFAULT_PROFILE, "pack.profile");
  if ("error" in parsedPackProfile) return parsedPackProfile;
  pack.profile = parsedPackProfile.profile;
  const parsedPackJurisdictions = parseJurisdictions(
    pack.jurisdictions ?? DEFAULT_JURISDICTIONS,
    "pack.jurisdictions",
  );
  if ("error" in parsedPackJurisdictions) return parsedPackJurisdictions;
  pack.jurisdictions = parsedPackJurisdictions.jurisdictions;
  if (!Array.isArray(pack.hats) || pack.hats.length === 0) {
    return { error: "pack.hats must include at least one hat" };
  }
  const invalidHat = pack.hats.find(
    (hat) =>
      !hat ||
      typeof hat !== "object" ||
      typeof hat.hat_id !== "string" ||
      !isSupportedHatId(hat.hat_id),
  );
  if (invalidHat !== undefined) {
    return { error: "pack.hats contains an unknown LegalPass hat_id" };
  }
  const duplicateHat = firstDuplicate(pack.hats.map((hat) => hat.hat_id).filter(Boolean) as string[]);
  if (duplicateHat) {
    return { error: "pack.hats entries must be unique by hat_id" };
  }
  if (pack.items !== undefined) {
    if (!Array.isArray(pack.items)) {
      return { error: "pack.items must be an array when provided" };
    }
    const invalidItem = pack.items.find(
      (item) =>
        !item ||
        typeof item !== "object" ||
        typeof (item as Record<string, unknown>).id !== "string" ||
        !String((item as Record<string, unknown>).id).trim(),
    );
    if (invalidItem !== undefined) {
      return { error: "pack.items entries must include a non-empty id" };
    }
    const duplicateItem = firstDuplicate(
      pack.items.map((item) => String((item as Record<string, unknown>).id)),
    );
    if (duplicateItem) {
      return { error: "pack.items entries must be unique by id" };
    }
  }
  const hasCitationVerifier = pack.hats.some(
    (hat) => hat?.enabled !== false && hat?.hat_id === "citation_verifier",
  );
  if (!hasCitationVerifier) {
    return { error: "citation_verifier hat is required for LegalPass packs" };
  }
  if (fixtureChecksForPack(pack).length === 0) {
    return { error: "at least one enabled phase-one LegalPass hat is required" };
  }

  return { pack };
}
