/**
 * legalpass-tool - MCP exposure for LegalPass.
 *
 * LegalPass is an issue-spotter only. These handlers expose the existing
 * LegalPass guardrails to MCP callers without pretending a full legal review
 * engine exists yet.
 */

import { createHash } from "node:crypto";

type DisclaimerLength = "chat" | "results" | "tos";

const DISCLAIMERS: Record<DisclaimerLength, string> = {
  chat:
    "LegalPass gives general legal information about contracts, not legal advice. " +
    "We are not a law firm. Using LegalPass does not create a lawyer-client " +
    "relationship. Laws change and vary by location. For decisions that " +
    "matter, talk to a qualified lawyer in your jurisdiction.",
  results:
    "Heads up: LegalPass is an information tool, not a law firm. The verdict " +
    "you are reading is generated by AI from patterns in similar documents. " +
    "It is not legal advice, not an opinion on your rights, and not a " +
    "substitute for review by a qualified lawyer. Your use of LegalPass does " +
    "not create a lawyer-client, solicitor-client or attorney-client " +
    "relationship, and what you tell us is not protected by legal " +
    "professional privilege. Laws change. They differ between countries, " +
    "states, and territories. For anything important, especially anything " +
    "you plan to sign, send, or rely on, please get advice from a lawyer " +
    "qualified in your jurisdiction before acting on that information.",
  tos:
    "LegalPass is a software tool operated by UnClick Operations Pty Ltd. It " +
    "scans contracts, terms of service, privacy policies, end-user licence " +
    "agreements, intellectual property agreements, and similar documents, " +
    "and produces a plain-English summary, called a verdict, that compares " +
    "clauses in your document with patterns observed in similar documents. " +
    "UnClick Operations Pty Ltd is not a law firm. It is not a regulated " +
    "legal practice in Australia, the United States, the United Kingdom, or " +
    "any other jurisdiction. Its directors and employees are not acting as " +
    "your lawyer, solicitor, or attorney. LegalPass cannot and does not give " +
    "legal advice, opinions, or recommendations about your legal rights, " +
    "remedies, defences, options, or strategies. LegalPass does not apply " +
    "law to the facts of your situation. Your use of LegalPass does not " +
    "create a lawyer-client, solicitor-client, or attorney-client relationship " +
    "between you and UnClick Operations Pty Ltd or anyone working for UnClick " +
    "Operations Pty Ltd. Information you upload or type into LegalPass is not " +
    "protected by legal professional privilege, attorney-client privilege, or " +
    "any equivalent doctrine. The verdict is informational only. It is " +
    "generated by artificial intelligence and may contain errors, omissions, " +
    "or out-of-date material. Laws change frequently. They vary between " +
    "countries, states, territories, and even between municipalities. A clause " +
    "that is common in one jurisdiction may be unusual or unenforceable in " +
    "another. You are responsible for confirming whether information in a " +
    "verdict is current and applies to your situation. Before you sign, send, " +
    "or rely on any document, get advice from a lawyer qualified in the " +
    "jurisdiction whose laws apply. LegalPass offers a Talk to a Lawyer " +
    "feature that introduces you to independent lawyers. Those lawyers are " +
    "not employees or agents of UnClick Operations Pty Ltd. Any engagement you " +
    "enter is between you and that lawyer. By using LegalPass you acknowledge " +
    "and accept these limits. To the maximum extent permitted by law, you use " +
    "LegalPass at your own risk.",
};

const FORBIDDEN_PHRASES: ReadonlyArray<{ phrase: string; reason: string }> = [
  { phrase: "should", reason: "directive verb - implies a recommendation" },
  { phrase: "must", reason: "directive verb - implies an obligation" },
  { phrase: "you need to", reason: "directive phrasing - implies an instruction" },
  { phrase: "you have to", reason: "directive phrasing - implies an instruction" },
  { phrase: "you are obligated", reason: "directive phrasing - implies a legal obligation" },
  { phrase: "do this", reason: "directive phrasing - implies an instruction" },
  { phrase: "we recommend", reason: "first-person recommendation - prohibited" },
  { phrase: "the right thing to do is", reason: "normative recommendation - prohibited" },
  { phrase: "this is illegal", reason: "definitive legal conclusion - prohibited" },
  { phrase: "this is enforceable", reason: "definitive legal conclusion - prohibited" },
  { phrase: "this is unenforceable", reason: "definitive legal conclusion - prohibited" },
  { phrase: "you will win", reason: "outcome prediction - prohibited" },
  { phrase: "you will lose", reason: "outcome prediction - prohibited" },
];

const ALLOWED_PHRASES = [
  "appears",
  "seems",
  "may",
  "might",
  "could",
  "consider",
  "in similar contracts",
  "in comparable agreements",
  "is unusual",
  "is common",
  "is typical",
  "is standard",
  "merits attention",
  "warrants review",
  "the regulatory landscape",
];

const FIXTURE_CHECKS: ReadonlyArray<{
  id: string;
  title: string;
  severity: "high" | "medium" | "low";
  terms: string[];
  finding: string;
}> = [
  {
    id: "privacy-controller-contact",
    title: "Controller or operator contact path",
    severity: "high",
    terms: ["contact", "privacy"],
    finding: "The public fixture text did not include the configured privacy contact signal.",
  },
  {
    id: "privacy-data-use",
    title: "Data collection and use disclosure",
    severity: "high",
    terms: ["collect", "use"],
    finding: "The public fixture text did not include the configured data collection and use signal.",
  },
  {
    id: "privacy-retention-transfer",
    title: "Retention or transfer disclosure",
    severity: "medium",
    terms: ["retain", "third party"],
    finding: "The public fixture text did not include the configured retention or transfer signal.",
  },
  {
    id: "tos-liability-indemnity",
    title: "Liability and indemnity visibility",
    severity: "high",
    terms: ["liability", "indemnity"],
    finding: "The public fixture text did not include the configured liability and indemnity signal.",
  },
  {
    id: "tos-variation-termination",
    title: "Variation or termination signal",
    severity: "medium",
    terms: ["terminate", "change"],
    finding: "The public fixture text did not include the configured variation or termination signal.",
  },
  {
    id: "tos-dispute-contact",
    title: "Dispute or support contact path",
    severity: "medium",
    terms: ["dispute", "support"],
    finding: "The public fixture text did not include the configured dispute or support signal.",
  },
  {
    id: "oss-manifest-licence",
    title: "Dependency licence manifest",
    severity: "high",
    terms: ["license", "dependency"],
    finding: "The public fixture text did not include the configured dependency licence signal.",
  },
  {
    id: "oss-attribution-copyleft",
    title: "Attribution or copyleft marker",
    severity: "medium",
    terms: ["attribution", "copyleft"],
    finding: "The public fixture text did not include the configured attribution or copyleft signal.",
  },
  {
    id: "oss-patent-notice",
    title: "Patent or notice signal",
    severity: "low",
    terms: ["patent", "notice"],
    finding: "The public fixture text did not include the configured patent or notice signal.",
  },
];

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function disclaimerLength(value: unknown): DisclaimerLength {
  return value === "chat" || value === "tos" ? value : "results";
}

function normalizeText(value: string): string {
  return value.toLocaleLowerCase("en-US").replace(/\s+/g, " ").trim();
}

function buildRunId(input: unknown): string {
  return `legalpass_${createHash("sha256")
    .update(JSON.stringify(input))
    .digest("hex")
    .slice(0, 12)}`;
}

function fixtureSummary(text: string) {
  const normalized = normalizeText(text);
  const items = FIXTURE_CHECKS.map((check) => {
    const passed = check.terms.every((term) => normalized.includes(normalizeText(term)));
    return {
      item_id: check.id,
      title: check.title,
      severity: check.severity,
      verdict: passed ? "check" : "fail",
      finding: passed
        ? `${check.title} appears in the public fixture text.`
        : `${check.finding} This is an issue-spotting flag only.`,
    };
  });
  const check = items.filter((item) => item.verdict === "check").length;
  const fail = items.filter((item) => item.verdict === "fail").length;
  return {
    total: items.length,
    check,
    fail,
    pass_rate: Math.round((check / items.length) * 100),
    items,
  };
}

export function lintLegalPassVerdict(text: string): Array<{ phrase: string; index: number; reason: string }> {
  const issues: Array<{ phrase: string; index: number; reason: string }> = [];
  for (const { phrase, reason } of FORBIDDEN_PHRASES) {
    const pattern = new RegExp(`\\b${escapeRegex(phrase)}\\b`, "gi");
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(text)) !== null) {
      issues.push({ phrase, index: match.index, reason });
    }
  }
  return issues.sort((a, b) => a.index - b.index);
}

export async function legalpassRun(args: Record<string, unknown>): Promise<unknown> {
  const packId = typeof args.pack_id === "string" && args.pack_id ? args.pack_id : "legalpass-mvp-v0";
  const target = parseTarget(args);
  const profile = typeof args.profile === "string" ? args.profile : "smoke";
  const jurisdictions = Array.isArray(args.jurisdictions) ? args.jurisdictions.filter((item) => typeof item === "string") : [];

  if (!target || typeof target.kind !== "string") {
    return { error: "target.kind or target_url is required" };
  }

  const fixtureText = typeof args.fixture_text === "string" ? args.fixture_text.trim() : "";
  if (fixtureText) {
    const summary = fixtureSummary(fixtureText);
    return {
      status: "complete",
      pass: "legalpass",
      run_id: buildRunId({ packId, target, profile, jurisdictions, fixtureText }),
      pack_id: packId,
      target,
      profile,
      jurisdictions,
      summary: {
        total: summary.total,
        check: summary.check,
        fail: summary.fail,
        pass_rate: summary.pass_rate,
      },
      items: summary.items,
      disclaimer: DISCLAIMERS.results,
      note:
        "LegalPass ran a deterministic public fixture issue-spotter pass. It did not fetch private data, draft legal text, or give legal advice.",
      safety: {
        issue_spotter_only: true,
        no_legal_advice: true,
        no_transactional_instrument: true,
      },
    };
  }

  return {
    status: "planned",
    pass: "legalpass",
    pack_id: packId,
    target,
    profile,
    jurisdictions,
    disclaimer: DISCLAIMERS.chat,
    note:
      "LegalPass MCP exposure is scaffold-only. It returns the guarded run plan now; full 12-hat execution lands in a later LegalPass engine chip.",
    safety: {
      issue_spotter_only: true,
      no_legal_advice: true,
      no_transactional_instrument: true,
    },
  };
}

function parseTarget(args: Record<string, unknown>): Record<string, unknown> | null {
  if (args.target && typeof args.target === "object" && !Array.isArray(args.target)) {
    return args.target as Record<string, unknown>;
  }

  if (typeof args.target_url === "string" && args.target_url.trim()) {
    return { kind: "url", url: args.target_url.trim() };
  }

  return null;
}

export async function legalpassVerdict(args: Record<string, unknown>): Promise<unknown> {
  const verdictText = typeof args.verdict_text === "string" ? args.verdict_text : "";
  const length = disclaimerLength(args.disclaimer_length);
  const issues = verdictText ? lintLegalPassVerdict(verdictText) : [];
  return {
    ok: issues.length === 0,
    safe_to_emit: issues.length === 0,
    issues,
    allowed_framing: ALLOWED_PHRASES,
    disclaimer_length: length,
    disclaimer: DISCLAIMERS[length],
  };
}
