import { describe, expect, it } from "vitest";
import {
  DEFAULT_SLOPPASS_SMELL_CHECKS,
  detectSlopSmells,
  getSlopPassSmellChecks,
} from "../smell-library.js";

describe("SlopPass smell library", () => {
  it("ships the deterministic chunk-1 smell checks", () => {
    expect(DEFAULT_SLOPPASS_SMELL_CHECKS.map((check) => check.id)).toEqual([
      "placeholder-logic",
      "broad-any-bypass",
      "unsafe-dynamic-execution",
      "secret-like-literal",
      "security-verification-bypass",
      "dependency-supply-chain-change",
      "package-lifecycle-script",
      "catch-all-fallback",
      "weak-assertion",
      "skipped-test",
      "tautological-test",
      "robustness-wording",
      "generated-copy-marker",
    ]);
  });

  it("detects deterministic slop signals without executing code", () => {
    const findings = detectSlopSmells([
      {
        path: "src/generated.ts",
        content: [
          "export const value: any = eval(input);",
          "try { run(); } catch { return null; }",
          "const token = 'demo_token_value_12345';",
          "test.skip('later', () => expect(true).toBe(true));",
          "expect(result).toBeDefined();",
          "// TODO generated by ChatGPT",
        ].join("\n"),
      },
    ]);

    expect(findings.map((finding) => finding.title)).toEqual([
      "Placeholder logic is still present",
      "Type safety was bypassed",
      "Dynamic code execution is present",
      "Secret-looking literal was detected",
      "Failure path is hidden by a catch-all fallback",
      "Weak test assertion is present",
      "Skipped or todo test is present",
      "Tautological test assertion is present",
      "Generated-copy marker needs human review",
      "Generated-copy marker needs human review",
    ]);
    expect(
      findings.filter((finding) => finding.title === "Generated-copy marker needs human review"),
    ).toHaveLength(2);
    expect(JSON.stringify(findings)).not.toContain("demo_token_value_12345");
    expect(findings).toContainEqual(
      expect.objectContaining({
        title: "Secret-looking literal was detected",
        evidence: "[redacted-secret-like-literal]",
      }),
    );
  });

  it("supports a narrowed smell-check set", () => {
    const checks = getSlopPassSmellChecks(["unsafe-dynamic-execution"]);
    const findings = detectSlopSmells(
      [{ path: "src/a.ts", content: "eval(userInput); // TODO" }],
      checks,
    );

    expect(findings).toHaveLength(1);
    expect(findings[0]?.title).toBe("Dynamic code execution is present");
  });

  it("redacts unquoted env-style and authorization secrets", () => {
    const fakeOpenAiToken = ["sk", "live", "do", "not", "print", "123456"].join("-");
    const fakeBearerToken = ["token", "that", "should", "not", "print", "98765"].join("-");
    const findings = detectSlopSmells([
      {
        path: ".env.example",
        content: [
          `OPENAI_API_KEY=${fakeOpenAiToken}`,
          `authorization: Bearer ${fakeBearerToken}`,
        ].join("\n"),
      },
    ]);

    const text = JSON.stringify(findings);
    expect(findings.filter((finding) => finding.title === "Secret-looking literal was detected")).toHaveLength(2);
    expect(text).not.toContain(fakeOpenAiToken);
    expect(text).not.toContain(fakeBearerToken);
  });

  it("redacts standalone common token shapes", () => {
    const fakeOpenAiToken = ["sk", "live", "standalone", "token", "123456"].join("-");
    const fakeGitHubToken = `ghp_${"abcdefghijklmnop1234567890"}`;
    const findings = detectSlopSmells([
      {
        path: "src/client.ts",
        content: [
          `const openAiToken = '${fakeOpenAiToken}';`,
          `const githubToken = '${fakeGitHubToken}';`,
        ].join("\n"),
      },
    ]);

    const text = JSON.stringify(findings);
    expect(findings.filter((finding) => finding.title === "Secret-looking literal was detected")).toHaveLength(2);
    expect(text).not.toContain(fakeOpenAiToken);
    expect(text).not.toContain(fakeGitHubToken);
  });

  it("flags concrete security verification bypasses", () => {
    const findings = detectSlopSmells([
      {
        path: "src/client.ts",
        content: [
          "process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';",
          "const agent = new https.Agent({ rejectUnauthorized: false });",
        ].join("\n"),
      },
    ]);

    expect(
      findings.filter((finding) => finding.title === "Security verification was bypassed"),
    ).toHaveLength(2);
    expect(findings).toContainEqual(
      expect.objectContaining({
        category: "grounding_api_reality",
        severity: "high",
        line: 1,
      }),
    );
  });

  it("flags diff-scoped dependency additions without treating full manifests as new", () => {
    const fullManifestFindings = detectSlopSmells([
      {
        path: "package.json",
        content: '    "left-pad": "^1.3.0"',
      },
    ]);
    const diffManifestFindings = detectSlopSmells([
      {
        path: "package.json",
        content: '    "left-pad": "^1.3.0"',
        start_line: 42,
      },
    ]);

    expect(
      fullManifestFindings.filter(
        (finding) => finding.title === "Dependency change needs package verification",
      ),
    ).toHaveLength(0);
    expect(diffManifestFindings).toContainEqual(
      expect.objectContaining({
        title: "Dependency change needs package verification",
        category: "maintenance_change_risk",
        severity: "info",
        line: 42,
      }),
    );
  });

  it("does not treat package metadata edits as dependency additions", () => {
    const findings = detectSlopSmells([
      {
        path: "package.json",
        content: [
          '  "name": "@unclick/sloppass",',
          '  "version": "0.1.1",',
          '  "type": "module"',
        ].join("\n"),
        start_line: 1,
      },
    ]);

    expect(
      findings.filter((finding) => finding.title === "Dependency change needs package verification"),
    ).toHaveLength(0);
  });

  it("flags diff-scoped package lifecycle scripts without treating full manifests as new", () => {
    const fullManifestFindings = detectSlopSmells([
      {
        path: "package.json",
        content: '    "postinstall": "node scripts/setup.js"',
      },
    ]);
    const diffManifestFindings = detectSlopSmells([
      {
        path: "package.json",
        content: [
          '    "postinstall": "node scripts/setup.js",',
          '    "postpublish": "node scripts/after-publish.js"',
        ].join("\n"),
        start_line: 17,
      },
    ]);

    expect(
      fullManifestFindings.filter(
        (finding) => finding.title === "Package lifecycle script needs supply-chain review",
      ),
    ).toHaveLength(0);
    expect(
      diffManifestFindings.filter(
        (finding) => finding.title === "Package lifecycle script needs supply-chain review",
      ),
    ).toHaveLength(2);
    expect(diffManifestFindings).toContainEqual(
      expect.objectContaining({
        title: "Package lifecycle script needs supply-chain review",
        category: "maintenance_change_risk",
        severity: "high",
        line: 17,
      }),
    );
    expect(diffManifestFindings).toContainEqual(
      expect.objectContaining({
        title: "Package lifecycle script needs supply-chain review",
        line: 18,
      }),
    );
  });
});
