import { describe, expect, it } from "vitest";
import {
  DEFAULT_SLOPPASS_SMELL_CHECKS,
  detectSlopSmells,
  getSlopPassSmellChecks,
} from "../smell-library.js";

describe("SlopPass smell library", () => {
  it("ships the deterministic chunk-1 smell checks", () => {
    expect(DEFAULT_SLOPPASS_SMELL_CHECKS.map((check) => check.id)).toEqual([
      "placeholder-logic",
      "broad-any-bypass",
      "unsafe-dynamic-execution",
      "secret-like-literal",
      "catch-all-fallback",
      "weak-assertion",
      "skipped-test",
      "tautological-test",
      "robustness-wording",
      "generated-copy-marker",
    ]);
  });

  it("detects deterministic slop signals without executing code", () => {
    const findings = detectSlopSmells([
      {
        path: "src/generated.ts",
        content: [
          "export const value: any = eval(input);",
          "try { run(); } catch { return null; }",
          "const token = 'demo_token_value_12345';",
          "test.skip('later', () => expect(true).toBe(true));",
          "expect(result).toBeDefined();",
          "// TODO generated by ChatGPT",
        ].join("\n"),
      },
    ]);

    expect(findings.map((finding) => finding.title)).toEqual([
      "Placeholder logic is still present",
      "Type safety was bypassed",
      "Dynamic code execution is present",
      "Secret-looking literal was detected",
      "Failure path is hidden by a catch-all fallback",
      "Weak test assertion is present",
      "Skipped or todo test is present",
      "Tautological test assertion is present",
      "Generated-copy marker needs human review",
      "Generated-copy marker needs human review",
    ]);
    expect(
      findings.filter((finding) => finding.title === "Generated-copy marker needs human review"),
    ).toHaveLength(2);
    expect(JSON.stringify(findings)).not.toContain("demo_token_value_12345");
    expect(findings).toContainEqual(
      expect.objectContaining({
        title: "Secret-looking literal was detected",
        evidence: "[redacted-secret-like-literal]",
      }),
    );
  });

  it("supports a narrowed smell-check set", () => {
    const checks = getSlopPassSmellChecks(["unsafe-dynamic-execution"]);
    const findings = detectSlopSmells(
      [{ path: "src/a.ts", content: "eval(userInput); // TODO" }],
      checks,
    );

    expect(findings).toHaveLength(1);
    expect(findings[0]?.title).toBe("Dynamic code execution is present");
  });

  it("redacts unquoted env-style and authorization secrets", () => {
    const fakeOpenAiToken = ["sk", "live", "do", "not", "print", "123456"].join("-");
    const fakeBearerToken = ["token", "that", "should", "not", "print", "98765"].join("-");
    const findings = detectSlopSmells([
      {
        path: ".env.example",
        content: [
          `OPENAI_API_KEY=${fakeOpenAiToken}`,
          `authorization: Bearer ${fakeBearerToken}`,
        ].join("\n"),
      },
    ]);

    const text = JSON.stringify(findings);
    expect(findings.filter((finding) => finding.title === "Secret-looking literal was detected")).toHaveLength(2);
    expect(text).not.toContain(fakeOpenAiToken);
    expect(text).not.toContain(fakeBearerToken);
  });

  it("redacts standalone common token shapes", () => {
    const fakeOpenAiToken = ["sk", "live", "standalone", "token", "123456"].join("-");
    const fakeGitHubToken = `ghp_${"abcdefghijklmnop1234567890"}`;
    const findings = detectSlopSmells([
      {
        path: "src/client.ts",
        content: [
          `const openAiToken = '${fakeOpenAiToken}';`,
          `const githubToken = '${fakeGitHubToken}';`,
        ].join("\n"),
      },
    ]);

    const text = JSON.stringify(findings);
    expect(findings.filter((finding) => finding.title === "Secret-looking literal was detected")).toHaveLength(2);
    expect(text).not.toContain(fakeOpenAiToken);
    expect(text).not.toContain(fakeGitHubToken);
  });
});
