-- SUPERSEDED — see 20260420050000_agent_trace.sql (same timestamp, sibling file)
--
-- This migration originally tried to create an `agent_activity` table for
-- per-turn agent-trace logging. That name collided with a pre-existing
-- usage-ledger table of the same name (columns: agent_id, action,
-- tool_slug, tokens_used) created by 20260418000000_agent_profiles.sql.
-- The trace table was renamed to `agent_trace` so both can coexist.
-- See the sibling migration for the actual schema.
--
-- This file is intentionally a no-op. The GitHub MCP used to publish the
-- rename doesn't support deletes, so the file was tombstoned rather than
-- removed. Can be `git rm`'d in a follow-up commit from a terminal with
-- push credentials; no schema depends on it.
