// PassGuard disclaimer-banner
// ---------------------------
// Three render-context disclaimers. Word counts are anchored to the brief:
//   chat    -> 42 words   (inline single-line context)
//   results -> 108 words  (results pane footer)
//   tos     -> 312 words  (terms of service / first-run modal)
//
// These strings are the legally reviewed defaults from the LegalPass brief
// (§7.1, see docs/legalpass-product-brief.md). Edits should round-trip
// through the brief and through legal review.
//
// They intentionally use the words "lawyer" / "attorney" because the
// disclaimer's whole purpose is to disclaim being one. The marketing-copy
// banned-words audit (qc_copy_audit) treats this module as exempt.

export type DisclaimerLength = "chat" | "results" | "tos";

const CHAT_DISCLAIMER =
  "LegalPass gives general legal information about contracts, not legal advice. " +
  "We are not a law firm. Using LegalPass does not create a lawyer-client " +
  "relationship. Laws change and vary by location. For decisions that " +
  "matter, talk to a qualified lawyer in your jurisdiction.";

const RESULTS_DISCLAIMER =
  "Heads up: LegalPass is an information tool, not a law firm. The verdict " +
  "you are reading is generated by AI from patterns in similar documents. " +
  "It is not legal advice, not an opinion on your rights, and not a " +
  "substitute for review by a qualified lawyer. Your use of LegalPass does " +
  "not create a lawyer-client, solicitor-client or attorney-client " +
  "relationship, and what you tell us is not protected by legal " +
  "professional privilege. Laws change. They differ between countries, " +
  "states, and territories. For anything important, especially anything " +
  "you plan to sign, send, or rely on, please get advice from a lawyer " +
  "qualified in your jurisdiction before acting on that information.";

const TOS_DISCLAIMER =
  "LegalPass is a software tool operated by UnClick Operations Pty Ltd. It " +
  "scans contracts, terms of service, privacy policies, end-user licence " +
  "agreements, intellectual property agreements, and similar documents, " +
  "and produces a plain-English summary, called a verdict, that compares " +
  "clauses in your document with patterns observed in similar documents. " +
  "UnClick Operations Pty Ltd is not a law firm. It is not a regulated " +
  "legal practice in Australia, the United States, the United Kingdom, or " +
  "any other jurisdiction. Its directors and employees are not acting as " +
  "your lawyer, solicitor, or attorney. LegalPass cannot and does not give " +
  "legal advice, opinions, or recommendations about your legal rights, " +
  "remedies, defences, options, or strategies. LegalPass does not apply " +
  "law to the facts of your situation. Your use of LegalPass does not " +
  "create a lawyer-client, solicitor-client, or attorney-client relationship " +
  "between you and UnClick Operations Pty Ltd or anyone working for UnClick " +
  "Operations Pty Ltd. Information you upload or type into LegalPass is not " +
  "protected by legal professional privilege, attorney-client privilege, or " +
  "any equivalent doctrine. The verdict is informational only. It is " +
  "generated by artificial intelligence and may contain errors, omissions, " +
  "or out-of-date material. Laws change frequently. They vary between " +
  "countries, states, territories, and even between municipalities. A clause " +
  "that is common in one jurisdiction may be unusual or unenforceable in " +
  "another. You are responsible for confirming whether information in a " +
  "verdict is current and applies to your situation. Before you sign, send, " +
  "or rely on any document, get advice from a lawyer qualified in the " +
  "jurisdiction whose laws apply. LegalPass offers a Talk to a Lawyer " +
  "feature that introduces you to independent lawyers. Those lawyers are " +
  "not employees or agents of UnClick Operations Pty Ltd. Any engagement you " +
  "enter is between you and that lawyer. By using LegalPass you acknowledge " +
  "and accept these limits. To the maximum extent permitted by law, you use " +
  "LegalPass at your own risk.";

const REGISTRY: Record<DisclaimerLength, string> = {
  chat: CHAT_DISCLAIMER,
  results: RESULTS_DISCLAIMER,
  tos: TOS_DISCLAIMER,
};

// Target word counts from the brief. Exposed for tests and audit.
export const DISCLAIMER_TARGETS: Record<DisclaimerLength, number> = {
  chat: 42,
  results: 108,
  tos: 312,
};

export function getDisclaimer(length: DisclaimerLength): string {
  return REGISTRY[length];
}

export function wordCount(text: string): number {
  const trimmed = text.trim();
  if (trimmed.length === 0) return 0;
  return trimmed.split(/\s+/).length;
}
