export type LocalModelTask = "chat" | "code" | "embeddings" | "ocr";

export interface LocalModelProfile {
  id: string;
  label: string;
  family: string;
  tasks: LocalModelTask[];
  parameterLabel: string;
  quantization: string;
  minVramGb: number;
  recommendedVramGb: number;
  minRamGb: number;
  diskGb: number;
  qualityScore: number;
  baseTokensPerSecond: number;
  notes: string;
}

export const LOCAL_MODEL_CATALOG: LocalModelProfile[] = [
  {
    id: "nomic-embed-text",
    label: "Nomic Embed Text",
    family: "Nomic",
    tasks: ["embeddings"],
    parameterLabel: "137M",
    quantization: "CPU friendly",
    minVramGb: 0,
    recommendedVramGb: 0,
    minRamGb: 8,
    diskGb: 1,
    qualityScore: 82,
    baseTokensPerSecond: 900,
    notes: "Good default for local memory and ContextPass-style retrieval indexing.",
  },
  {
    id: "bge-m3",
    label: "BGE-M3",
    family: "BAAI",
    tasks: ["embeddings"],
    parameterLabel: "568M",
    quantization: "CPU friendly",
    minVramGb: 0,
    recommendedVramGb: 0,
    minRamGb: 8,
    diskGb: 3,
    qualityScore: 88,
    baseTokensPerSecond: 650,
    notes: "Strong multilingual embedding model for local retrieval.",
  },
  {
    id: "llama-3.2-3b-instruct-q4",
    label: "Llama 3.2 3B Instruct Q4",
    family: "Meta",
    tasks: ["chat"],
    parameterLabel: "3B",
    quantization: "Q4",
    minVramGb: 3,
    recommendedVramGb: 4,
    minRamGb: 8,
    diskGb: 3,
    qualityScore: 66,
    baseTokensPerSecond: 62,
    notes: "Small chat model for low VRAM machines and fast offline drafts.",
  },
  {
    id: "mistral-7b-instruct-q4",
    label: "Mistral 7B Instruct Q4",
    family: "Mistral",
    tasks: ["chat"],
    parameterLabel: "7B",
    quantization: "Q4",
    minVramGb: 4,
    recommendedVramGb: 6,
    minRamGb: 16,
    diskGb: 5,
    qualityScore: 74,
    baseTokensPerSecond: 44,
    notes: "Reliable local assistant baseline for simple chat and summarization.",
  },
  {
    id: "llama-3.1-8b-instruct-q4",
    label: "Llama 3.1 8B Instruct Q4",
    family: "Meta",
    tasks: ["chat"],
    parameterLabel: "8B",
    quantization: "Q4",
    minVramGb: 5,
    recommendedVramGb: 8,
    minRamGb: 16,
    diskGb: 6,
    qualityScore: 78,
    baseTokensPerSecond: 38,
    notes: "Comfortable default for 8GB VRAM and up.",
  },
  {
    id: "qwen2.5-coder-7b-q4",
    label: "Qwen2.5 Coder 7B Q4",
    family: "Qwen",
    tasks: ["code"],
    parameterLabel: "7B",
    quantization: "Q4",
    minVramGb: 5,
    recommendedVramGb: 8,
    minRamGb: 16,
    diskGb: 6,
    qualityScore: 80,
    baseTokensPerSecond: 36,
    notes: "Good local coding model for routine edits and reviews.",
  },
  {
    id: "qwen2.5-coder-14b-q4",
    label: "Qwen2.5 Coder 14B Q4",
    family: "Qwen",
    tasks: ["code"],
    parameterLabel: "14B",
    quantization: "Q4",
    minVramGb: 10,
    recommendedVramGb: 12,
    minRamGb: 24,
    diskGb: 10,
    qualityScore: 87,
    baseTokensPerSecond: 24,
    notes: "Better code quality when 12GB VRAM is available.",
  },
  {
    id: "llava-13b-q4",
    label: "LLaVA 13B Q4",
    family: "LLaVA",
    tasks: ["ocr"],
    parameterLabel: "13B",
    quantization: "Q4",
    minVramGb: 10,
    recommendedVramGb: 12,
    minRamGb: 24,
    diskGb: 12,
    qualityScore: 76,
    baseTokensPerSecond: 16,
    notes: "Local image understanding baseline when privacy matters more than speed.",
  },
  {
    id: "paddleocr-vl-local",
    label: "PaddleOCR-VL Local",
    family: "PaddleOCR",
    tasks: ["ocr"],
    parameterLabel: "OCR stack",
    quantization: "mixed",
    minVramGb: 8,
    recommendedVramGb: 12,
    minRamGb: 16,
    diskGb: 8,
    qualityScore: 84,
    baseTokensPerSecond: 22,
    notes: "Document and screenshot extraction candidate for a self-hosted ContextPass lane.",
  },
  {
    id: "mixtral-8x7b-q4",
    label: "Mixtral 8x7B Q4",
    family: "Mistral",
    tasks: ["chat", "code"],
    parameterLabel: "8x7B",
    quantization: "Q4",
    minVramGb: 24,
    recommendedVramGb: 32,
    minRamGb: 48,
    diskGb: 28,
    qualityScore: 90,
    baseTokensPerSecond: 18,
    notes: "High-quality local reasoning for larger GPU setups.",
  },
  {
    id: "llama-3.1-70b-q4",
    label: "Llama 3.1 70B Q4",
    family: "Meta",
    tasks: ["chat", "code"],
    parameterLabel: "70B",
    quantization: "Q4",
    minVramGb: 40,
    recommendedVramGb: 48,
    minRamGb: 64,
    diskGb: 45,
    qualityScore: 94,
    baseTokensPerSecond: 11,
    notes: "Only recommended for 40GB+ VRAM or multi-GPU local rigs.",
  },
];
